import { IconProp } from "@fortawesome/fontawesome-svg-core";
import { faBaby, faJetFighterUp, faLemon, faUserSlash, faViruses, faUserAstronaut, faFrog, faRobot, faShieldDog, faHandSpock, faHandHoldingDollar } from '@fortawesome/free-solid-svg-icons';

export interface IUser {
	id: number;
	avatar: string;
	nickname: string;
	mailAddress: string;
	coalition: string;
	nbGames: number;
	score: number;
	rank: number;
	isLogged: boolean;
	friendsList : IUser[];
	blockList : IUser[];
	pendingList : IUser[];
	isActive : boolean;
}

export interface IAchievement {
	icon : IconProp;
	title : string;
	description : string;
	wasAchieved: boolean;
}

export const users : IUser[] =  [
	{
		id: 0,
		avatar: "/assets/avatar2.png",
		nickname: "John",
		mailAddress: "",
		coalition: "Federation",
		nbGames: 14,
		score: 1000,
		rank: 1,
		isLogged:false,
		friendsList : [],
		blockList : [],
		pendingList : [],
		isActive : false,
	},{
		id: 1,
		avatar: "/assets/avatar3.png",
		nickname: "Caitlyn",
		mailAddress: "",
		coalition: "Assembly",
		nbGames: 8,
		score: 750,
		rank: 4,
		isLogged:false,
		friendsList : [],
		blockList : [],
		pendingList : [],
		isActive : false,
	},{
		id: 2,
		avatar: "/assets/avatar3.png",
		nickname: "Viktor",
		mailAddress: "",
		coalition: "Federation",
		nbGames: 3,
		score: 52,
		rank: 9,
		isLogged:false,
		friendsList : [],
		blockList : [],
		pendingList : [],
		isActive : false,
	},{
		id: 3,
		avatar: "/assets/avatar2.png",
		nickname: "Sion",
		mailAddress: "",
		coalition: "Assembly",
		nbGames: 12,
		score: 896,
		rank: 3,
		isLogged:false,
		friendsList : [],
		blockList : [],
		pendingList : [],
		isActive : false,
	},{
		id: 4,
		avatar: "/assets/avatar1.png",
		nickname: "Jinx",
		mailAddress: "",
		coalition: "Federation",
		nbGames: 13,
		score: 963,
		rank: 2,
		isLogged:false,
		friendsList : [],
		blockList : [],
		pendingList : [],
		isActive : false,
  	},{
		id: 5,
		avatar: "/assets/avatar2.png",
		nickname: "Malphite",
		mailAddress: "",
		coalition: "Order",
		nbGames: 2,
		score: 89,
		rank: 8,
		isLogged:false,
		friendsList : [],
		blockList : [],
		pendingList : [],
		isActive : false,
  	},{
		id: 6,
		avatar: "/assets/avatar3.png",
		nickname: "Le Blanc",
		mailAddress: "",
		coalition: "Alliance",
		nbGames: 6,
		score: 123,
		rank: 7,
		isLogged:false,
		friendsList : [],
		blockList : [],
		pendingList : [],
		isActive : false,
	},{
		id: 7,
		avatar: "/assets/avatar2.png",
		nickname: "Lee Sin",
		mailAddress: "",
		coalition: "Alliance",
		nbGames: 15,
		score: 450,
		rank: 6,
		isLogged:false,
		friendsList : [],
		blockList : [],
		pendingList : [],
		isActive : true,
	},{
		id: 8,
		avatar: "/assets/avatar1.png",
		nickname: "Lulu",
		mailAddress: "",
		coalition: "Order",
		nbGames: 8,
		score: 487,
		rank: 5,
		isLogged: true,
		friendsList : [
			{
				id: 9,
				avatar: "/assets/avatar3.png",
				nickname: "Diana",
				mailAddress: "",
				coalition: "Alliance",
				nbGames: 2,
				score: 28,
				rank: 10,
				isLogged:false,
				friendsList : [],
				blockList : [],
				pendingList : [],
				isActive : true,
			},
			{
				id: 7,
				avatar: "/assets/avatar2.png",
				nickname: "Lee Sin",
				mailAddress: "",
				coalition: "Alliance",
				nbGames: 15,
				score: 450,
				rank: 6,
				isLogged:false,
				friendsList : [],
				blockList : [],
				pendingList : [],
				isActive : true,
			},
			{
				id: 4,
				avatar: "/assets/avatar1.png",
				nickname: "Jinx",
				mailAddress: "",
				coalition: "Federation",
				nbGames: 13,
				score: 963,
				rank: 2,
				isLogged:false,
				friendsList : [],
				blockList : [],
				pendingList : [],
				isActive : false,
			}
		],
		blockList : [
			{
				id: 6,
				avatar: "/assets/avatar3.png",
				nickname: "Le Blanc",
				mailAddress: "",
				coalition: "Alliance",
				nbGames: 6,
				score: 123,
				rank: 7,
				isLogged:false,
				friendsList : [],
				blockList : [],
				pendingList : [],
				isActive : false,
			},
			{
				id: 5,
				avatar: "/assets/avatar2.png",
				nickname: "Malphite",
				mailAddress: "",
				coalition: "Order",
				nbGames: 2,
				score: 89,
				rank: 8,
				isLogged:false,
				friendsList : [],
				blockList : [],
				pendingList : [],
				isActive : false,
			  }
		],
		pendingList : [
			{
				id: 3,
				avatar: "/assets/avatar2.png",
				nickname: "Sion",
				mailAddress: "",
				coalition: "Assembly",
				nbGames: 12,
				score: 896,
				rank: 3,
				isLogged:false,
				friendsList : [],
				blockList : [],
				pendingList : [],
				isActive : false,
			},
			{
				id: 2,
				avatar: "/assets/avatar3.png",
				nickname: "Viktor",
				mailAddress: "",
				coalition: "Federation",
				nbGames: 3,
				score: 52,
				rank: 9,
				isLogged:false,
				friendsList : [],
				blockList : [],
				pendingList : [],
				isActive : false,
			}
		],
		isActive : true,
	},{
		id: 9,
		avatar: "/assets/avatar3.png",
		nickname: "Diana",
		mailAddress: "",
		coalition: "Alliance",
		nbGames: 2,
		score: 28,
		rank: 10,
		isLogged:false,
		friendsList : [],
		blockList : [],
		pendingList : [],
		isActive : true,
	}];


export const achievements: IAchievement[] = [
	{
		icon : faBaby,
		title : "Baby steps",
		description: "Played the game for the first time",
		wasAchieved: false,
	},
	{
		icon : faJetFighterUp,
		title : "Veteran",
		description: "Played 10 games",
		wasAchieved: false,
	},
	{
		icon : faLemon,
		title : "Easy peasy lemon squeezy",
		description: "Won 3 games in a row",
		wasAchieved: false,
	},
	{
		icon : faUserSlash,
		title : "It's my lil bro playing",
		description: "Lost 3 games in a row",
		wasAchieved: false,
	},
	{
		icon : faViruses,
		title : "Social butterfly",
		description: "Added 3 friends",
		wasAchieved: false,
	},
	{
		icon : faUserAstronaut,
		title : "Influencer",
		description: "Added 10 friends",
		wasAchieved: false,
	},
	{
		icon : faFrog,
		title : "Cosmetic change",
		description: "Updated their profile picture once",
		wasAchieved: false,
	},
	{
		icon : faRobot,
		title : "Existential crisis",
		description: "Changed their nickname",
		wasAchieved: false,
	},
	{
		icon : faShieldDog,
		title : "Safety first",
		description: "Activated the 2FA authentification",
		wasAchieved: false,
	},
	{
		icon : faHandSpock,
		title : "My safe place",
		description: "Created their first channel",
		wasAchieved: false,
	},
	{
		icon : faHandHoldingDollar,
		title : "Pay to Win",
		description: "Donated to have an in-game advantage",
		wasAchieved: false,
	},
];

