import './App.css';

function App() {
  return (
    <div className="App">
      <header id="navbar"> 
        <div class="nav-elements">

        <label id="burger-menu" for="check">
            <input type="checkbox" id="check"/> 
            <span></span>
            <span></span>
            <span></span>
        </label>

        </div>
        <div class="nav-elements nav-title">NOTRE PONG</div>
        <div class="nav-elements avatar"></div>
      </header>

    <section id="main-content">
        <div id="menu">
          <div>
            <span>LEADERBOARD</span>
          </div>
          <div>
            <i class="fa-solid fa-user-group"></i>
            <span>FRIENDS</span>
          </div>
          <div>
            <i class="fa-regular fa-address-card"></i>
            <span>PROFILE</span>
          </div>
        </div>

        <div id="play-screen">
          <button>PRESS TO PLAY</button>
        </div>
      
        <div id="chat">
          <h5>CHAT</h5>
        </div>

    </section>
    
    <footer> This website was not generated by an AI :) </footer>
    </div>
  );
}

export default App;
