
import { Routes, Route } from 'react-router-dom';
import { useEffect, useState } from 'react';
import './App.css';
import Header from './components/Header';
import Home from './pages/Home'
import { Leaderboard } from './pages/Leaderboard';
import { FriendsList } from './pages/FriendsList';

function App() {

  const [theme, setTheme] = useState('dark');

  useEffect(() => {
    const storedTheme = localStorage.getItem('theme');
    if (storedTheme) {
      setTheme(storedTheme);
    }
  }, []); // [] specifies the dependencies array (if empty : runs only when component mounts)

  const toggleTheme = () => {
    const newTheme = theme === 'dark' ? 'kawaii' : 'dark';
    setTheme(newTheme);
    localStorage.setItem('theme', newTheme);
  };

  return (
    <div id='app' className={`App ${theme}`}>

    <Header 
      theme={theme} 
      toggleTheme={toggleTheme}
    />

    <section id="main-content">
      {/* <div id="menu"></div> */}

    <Routes>
      <Route path="/" element={<Home />} />
      <Route path="/leaderboard" element={<Leaderboard />} />
      <Route path="/friends" element={<FriendsList />} />
    </Routes>
   
      {/* <div id="chat">
        <h5>CHAT</h5>
      </div> */}
    </section> 

    <footer> This website was not generated by an AI :) </footer>
    </div>
  );
}

export default App;
